### ISSUE TITLE
Consider renaming to thonny-flake8

### ISSUE THREAD

**Issue by andypiper** [Bigjango13/thonny-flake#1]
Currently, I can search for `thonny-` in the Thonny plugins window to find the majority of Thonny plugins on PyPi (the same applies to `thonny` and `thonny*`) - ThonnyFlake8 does not show up unless I enter `ThonnyFlake8` or `thonnyf`.

I'd like to suggest renaming the package just for consistency with other plugin packages.

**Comment by andypiper** [comment]
Just checked and the Thonny plugin documentation also [recommends this](https://github.com/thonny/thonny/wiki/Plugins#how-to-package-and-distribute-your-plug-in):

> Just make sure your distribution name starts with thonny- and you have specified supported Thonny version range under dependencies.

**Comment by Bigjango13** [comment]
Renamed, thank you. Unfortunately PyPi wouldn't let me use `thonny-flake8` because it was too similar to `ThonnyFlake8` so instead I renamed it to `thonny-flake`.
